services:
  authelia-manager:
    image: ghcr.io/jmahlman/authelia-manager:latest
    container_name: authelia-manager
    ports:
      - 9999:5000
    environment:
      - SECRET_KEY=${SECRET_KEY:-}
    restart: unless-stopped
